# Generated by Django 3.1.3 on 2020-11-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201108_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passresetemail',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
