# Generated by Django 3.1.3 on 2020-11-10 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201108_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('create_appointment', 'Determines If A User Can Create An Appointment'), ('accept_appointment', 'Determines If A User can accepts an appointment'), ('view_appointment_grid', 'Determines If A User Can View The Appointment Calendar')]},
        ),
    ]
