# Generated by Django 3.1.3 on 2020-11-16 03:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201110_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
