# Generated by Django 3.1.3 on 2020-11-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20201112_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='issue',
            field=models.CharField(default='DEFAULT', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='post_summary',
            field=models.CharField(default='DEFAULT', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('OP', 'Pending'), ('ON', 'Ongoing'), ('CL', 'Completed')], default='CL', max_length=2),
        ),
    ]
