# Generated by Django 3.1.3 on 2020-11-12 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_appointment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='scheduled',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('OP', 'Pending'), ('ON', 'Ongoing'), ('CL', 'Completed'), ('SC', 'Scheduled')], default='CL', max_length=2),
        ),
    ]
