# Generated by Django 3.1.3 on 2021-02-12 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0010_auto_20201118_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='join_code',
            field=models.CharField(default='09hm6e92', max_length=8),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
