# Generated by Django 3.1.3 on 2021-02-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20210212_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='join_code',
        ),
    ]
